Repository jjmonsalveg/front-end-path, pull requests merged in 2023-09, with the labels that each got.

#98 feat(foreach): Add other forms to itereate
  README.md
  learn_enough_js_tutorial/foreach.js
Labels: classroom, js

#104 Hacer ejercicio 14.1.3
  sample_jekyll/_includes/head.html
  sample_jekyll/css/main.css
  sample_jekyll/index.html
Labels: css, html, homework

#103 Classroom Css
  sample_jekyll/_includes/head.html
  sample_jekyll/blog/index.html
  sample_jekyll/images/favicon.png
Labels: css, classroom, jekyll, html

#102 Hacer ejercicios 5.4.1, 6.1.1 y 6.2.1 de js
  learn_enough_js_tutorial/exercises/exercise_5.4.1.js
  learn_enough_js_tutorial/exercises/exercise_6.1.1.js
  learn_enough_js_tutorial/exercises/exercise_6.2.1.js
Labels: js, homework

#100 functional programming
  README.md
  learn_enough_js_tutorial/functional.js
  learn_enough_js_tutorial/palindrome.js
Labels: classroom, js

#106 Hacer parte 1 ejercicio 6.3.4·
  learn_enough_js_tutorial/exercises/exercise_6.3.4.js
Labels: js, homework
