Repository jjmonsalveg/front-end-path, pull requests merged in 2023-10, with the labels that each got.

#108 Hacer ejercicio 7.1.1
  learn_enough_js_tutorial/exercises/exercise_7.1.1.js
Labels: js, homework

#107 feat(js): Objects
  learn_enough_js_tutorial/palindrome.js
Labels: classroom, js

#109 Hacer ejercicio 7.3.1
  README.md
  learn_enough_js_tutorial/exercises/exercise_7.3.1.js
Labels: js, homework

#105 Class css
  .markdownlint.yaml
  README.md
  images/learn-enough-html/grid/alignment.png
  images/learn-enough-html/grid/auto-types.png
  sample_jekyll/grid.html
Labels: css, classroom, jekyll, html

#110 TDD chapter 8
  README.md
  learn_enough_js_tutorial/palindrome/README.md
  learn_enough_js_tutorial/palindrome/index.js
  learn_enough_js_tutorial/palindrome/package.json
  learn_enough_js_tutorial/palindrome/test/test.js
Labels: classroom, js
